<?php

$produk = [
    [
        'kategori' => 'hoodie',
        'nama' => 'Hoodie Byone 1',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Jaket/hbyone1.jpg',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 'hoodie',
        'nama' => 'Hoodie Byone 2',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Jaket/hbyone2.webp',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 'hoodie',
        'nama' => 'Hoodie Byone 3',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Jaket/hbyone3.webp',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 'hoodie',
        'nama' => 'Hoodie Byone 4',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Jaket/hbyone4.webp',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 'hoodie',
        'nama' => 'Hoodie Byone 5',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Jaket/hbyone5.jpg',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 'hoodie',
        'nama' => 'Hoodie Byone 6',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Jaket/hbyone6.jpg',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 'hoodie',
        'nama' => 'Hoodie Byone 7',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Jaket/hbyone7.jpg',
        'bahan' => '',
        'stok' => '',
    ],

    [
        'kategori' => 'jeans',
        'nama' => 'Jeans Denim 1',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Jeans/jdenim1.jpg',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 'jeans',
        'nama' => 'Jeans Denim 2',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Jeans/jdenim2.jpg',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 'jeans',
        'nama' => 'Jeans Denim 3',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Jeans/jdenim3.jpg',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 'jeans',
        'nama' => 'Jeans Denim 4',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Jeans/jdenim4.jpg',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 'jeans',
        'nama' => 'Jeans Denim 5',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Jeans/jdenim5.jpg',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 'jeans',
        'nama' => 'Jeans Denim 6',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Jeans/jdenim5.jpg',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 'jeans',
        'nama' => 'Jeans Denim 7',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Jeans/jdenim7.jpg',
        'bahan' => '',
        'stok' => '',
    ],

    [
        'kategori' => 'kemeja',
        'nama' => 'Kemeja Byone 1',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Kemeja/kbyone1.webp',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 'kemeja',
        'nama' => 'Kemeja Byone 2',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Kemeja/kbyone2.webp',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 'kemeja',
        'nama' => 'Kemeja Byone 3',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Kemeja/kbyone3.webp',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 'kemeja',
        'nama' => 'Kemeja Byone 4',
        'harga' => 'Rp. 100.000',
        'image' => 'images/Kemeja/kbyone4.webp',
        'bahan' => '',
        'stok' => '',
    ],

    [
        'kategori' => 't-shirt',
        'nama' => 'T-Shirt Byone 1',
        'harga' => 'Rp. 100.000',
        'image' => 'images/T-Shirt/tbyone1.webp',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 't-shirt',
        'nama' => 'T-Shirt Byone 2',
        'harga' => 'Rp. 100.000',
        'image' => 'images/T-Shirt/tbyone2.webp',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 't-shirt',
        'nama' => 'T-Shirt Byone 3',
        'harga' => 'Rp. 100.000',
        'image' => 'images/T-Shirt/tbyone3.webp',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 't-shirt',
        'nama' => 'T-Shirt Byone 4',
        'harga' => 'Rp. 100.000',
        'image' => 'images/T-Shirt/tbyone4.webp',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 't-shirt',
        'nama' => 'T-Shirt Byone 5',
        'harga' => 'Rp. 100.000',
        'image' => 'images/T-Shirt/tbyone5.webp',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 't-shirt',
        'nama' => 'T-Shirt Byone 6',
        'harga' => 'Rp. 100.000',
        'image' => 'images/T-Shirt/tbyone6.webp',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 't-shirt',
        'nama' => 'T-Shirt Byone 7',
        'harga' => 'Rp. 100.000',
        'image' => 'images/T-Shirt/tbyone7.webp',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 't-shirt',
        'nama' => 'T-Shirt Byone 8',
        'harga' => 'Rp. 100.000',
        'image' => 'images/T-Shirt/tbyone8.webp',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 't-shirt',
        'nama' => 'T-Shirt Byone 9',
        'harga' => 'Rp. 100.000',
        'image' => 'images/T-Shirt/tbyone9.jpg',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 't-shirt',
        'nama' => 'T-Shirt Byone 10',
        'harga' => 'Rp. 100.000',
        'image' => 'images/T-Shirt/tbyone10.jpg',
        'bahan' => '',
        'stok' => '',
    ],
    [
        'kategori' => 't-shirt',
        'nama' => 'T-Shirt Byone 11',
        'harga' => 'Rp. 100.000',
        'image' => 'images/T-Shirt/tbyone11.jpg',
        'bahan' => '',
        'stok' => '',
    ],
];

$rekomendasi_produk = [
    '0' => $produk[0],
    '1' => $produk[1],
    '7' => $produk[7],
    '8' => $produk[8],
    '14' => $produk[14],
    '15' => $produk[15],
    '18' => $produk[18],
    '19' => $produk[19],
];

$kategori = [
    'hoodie' => 'Hoodie',
    't-shirt' => 'T-Shirt',
    'jeans' => 'Jeans',
    'kemeja' => 'Kemeja',
];
